#!/usr/bin/perl
use EPrints qw();

use strict;
use warnings;

use EPrints::ScreenProcessor;

my $eprints = EPrints->new;
my $repo = $eprints->current_repository();

EPrints::ScreenProcessor->process(
    screenid => 'REF2029_Review::Respond',
    session => $repo,
    url => $repo->config( "http_cgiroot" ) . "/ref2029/review" 
);

$repo->terminate;
